version: '3'
services:  
  wp:
    image: 'wordpress:latest'
    container_name: wp
    ports:
      - '8080:80'
      - '443:433'
    restart: always
    environment:
      WORDPRESS_DB_HOST: 192.168.1.111:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
        - wp_data:/var/www/html    

volumes:
  wp_data:
