# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "db" do |db|	
		db.vm.box = "ubuntu/bionic64"
		db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		db.vm.network "public_network", ip:"192.168.1.111", bridge:	"wlp2s0"	  
		db.vm.provision "file", source: "~/lab/lab-02/docker-compose-db.yml", destination: "~/docker-compose.yml" 
		db.vm.provision "shell", path: "db.sh"
	end
	config.vm.define "ubuntu" do |ubuntu|	
		ubuntu.vm.box = "ubuntu/bionic64"
		ubuntu.ssh.insert_key = false
		ubuntu.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		ubuntu.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		ubuntu.vm.network "public_network", ip:"192.168.1.110", bridge:	"wlp2s0"  
		ubuntu.vm.provision "file", source: "~/lab/lab-02/docker-compose-wp.yml", destination: "~/docker-compose.yml" 
		ubuntu.vm.provision "shell", path: "wordpress.sh"
	end

end
