# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|	
	  ubuntu.vm.box = "ubuntu/bionic64"
	  ubuntu.vm.network "public_network", ip:"192.168.2.171"	  
	  ubuntu.vm.provision "file", source: "~/Documentos/lab2/docker-compose.yml", destination: "~/docker-compose.yml" 
	  ubuntu.vm.provision "shell", path: "wordpress.sh"
  end
#  config.vm.define "ubuntu" do |ubuntu|	
#	ubuntu.vm.box = "ubuntu/bionic64"
#	ubuntu.vm.network "public_network", ip:"192.168.2.151"	  
#	ubuntu.vm.provision "file", source: "~/Documentos/lab2/docker-compose.yml", destination: "~/docker-compose.yml" 
#	ubuntu.vm.provision "shell", inline: <<-SHELL
#		 sudo apt update
#		 sudo apt install -y docker.io docker-compose
#		 sudo systemctl enable --now docker docker.socket containerd
#		 sudo su
#		 docker-compose up -d
#		 docker ps
#		 exit
#	SHELL
#end
end
