# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "ubuntu" do |ubuntu|	
		ubuntu.vm.box = "ubuntu/bionic64"
		ubuntu.ssh.insert_key = false
		  ubuntu.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
		ubuntu.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
		ubuntu.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		ubuntu.vm.network "public_network", ip:"192.168.1.171", bridge:	"wlp2s0"  
		ubuntu.vm.provision "file", source: "~/labmadson/lab/lab-02/docker-compose.yml", destination: "~/docker-compose.yml" 
		ubuntu.vm.provision "shell", path: "wordpress.sh"
	end
	config.vm.define "db" do |db|	
		db.vm.box = "ubuntu/bionic64"
		db.vm.network "public_network", ip:"192.168.1.151", bridge:	"wlp2s0"	  
		db.vm.provision "file", source: "~/labmadson/lab/lab-02/docker-compose1.yml", destination: "~/docker-compose.yml" 
		db.vm.provision "shell", path: "db.sh"
	end

end
